### ISSUE TITLE
Hey thank you

### ISSUE THREAD

**Issue by xentzenith** [CityIsBetter/CityIsBetter#1]
Hey thank you for following me, I followed you back can you just give star last 2 repository which is

https://github.com/xentzenith/x3nos

https://github.com/xentzenith/weather-final-project

I will yours too. Just drop link after starring.

**Comment by CityIsBetter** [comment]
Done!, 

https://github.com/CityIsBetter/NoteScape
https://github.com/CityIsBetter/AcademiaHUB

**Comment by xentzenith** [comment]
Thank you a lot man.

**Comment by xentzenith** [comment]
You can close this issue.
